# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: asaiz-lo <asaiz-lo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/19 17:17:28 by asaiz-lo          #+#    #+#              #
#    Updated: 2025/10/27 13:56:43 by asaiz-lo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
BONUS_NAME = .bonus
SRCS = ft_atoi.c ft_isprint.c ft_isspace.c ft_issign.c ft_putchar_fd.c ft_strjoin.c ft_strrchr.c ft_putendl_fd.c ft_strlcat.c ft_strtrim.c ft_bzero.c  \
ft_memchr.c ft_putnbr_fd.c ft_strlcpy.c ft_itoa.c ft_substr.c ft_calloc.c  ft_memcmp.c ft_putstr_fd.c ft_tolower.c ft_isalnum.c  ft_split.c \
ft_strlen.c ft_toupper.c ft_isalpha.c  ft_memcpy.c ft_strchr.c ft_strcmp.c ft_strnchr.c ft_strmapi.c ft_isascii.c ft_memmove.c ft_strdup.c \
ft_strncmp.c ft_isdigit.c  ft_memset.c ft_striteri.c ft_strnstr.c gnl/get_next_line.c \

BONUS = ft_lstnew_bonus.c ft_lstclear_bonus.c ft_lstadd_back_bonus.c ft_lstsize_bonus.c ft_lstadd_front_bonus.c ft_lstlast_bonus.c \
        ft_lstiter_bonus.c ft_lstdelone_bonus.c ft_lstmap_bonus.c

OBJS = $(SRCS:.c=.o)
BONUS_OBJS = $(BONUS:.c=.o)
CC = cc
CFLAGS = -Wall -Werror -Wextra -g3
AR = ar
ARFLAGS = rcs
RM = rm -f

all: $(NAME)
$(NAME): $(OBJS)
	$(AR) $(ARFLAGS) $(NAME) $(OBJS)
$(BONUS_NAME): $(OBJS) $(BONUS_OBJS)
	$(AR) $(ARFLAGS) $(NAME) $(OBJS) $(BONUS_OBJS)
	$(AR) $(ARFLAGS) $(BONUS_NAME) $(OBJS) $(BONUS_OBJS)
bonus: $(BONUS_NAME)
clean:
	$(RM) $(OBJS) $(BONUS_OBJS)
fclean: clean
	$(RM) $(NAME)
re: fclean all
.PHONY: all bonus clean fclean re